# Generated by Django 3.0.4 on 2020-03-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
