# Generated by Django 3.0.4 on 2020-03-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
